### ISSUE TITLE
Issue with tf-plan

### ISSUE THREAD

**Issue by ramonpereira** [thiagopbueno/tf-plan#2]
Hi @thiagopbueno,

I'm working with @miquelramirez in a project here in Melbourne, and we're using your tf-plan planner to play with some of the linear (and non-linear) domains we have formalized. Actually, we're trying to use some RDDL domains generated/translated from Tarski as input into your planner, and the planner has returned the following error for one of the domains (lqg_nav_1d_001.rddl in the zip file):

```
Running tf-plan v0.4.5 ...
>> RDDL:            ../rddl/deterministic/lqg_nav_1d_001.rddl
>> Planning mode:   offline
>> Horizon:         10
>> Batch size:      32
>> Training epochs: 1000
>> Learning rate:   0.01

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1626, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 1 and 2 for 'action_optimizer/trajectory/while/reward/Select' (op: 'Select') with input shapes: [32,1], [32], [32].
```

We are not sure, but we think that it might be related to the cpfs{} defined in our domains.
We have tried to use other RDDL domains and the planner has worked properly.
If you have time, please try to use the other domains in the zip file.

[rddls_from_tarski.zip](https://github.com/thiagopbueno/tf-plan/files/2609757/rddls_from_tarski.zip)

Regards.
Ramon F. P.

**Comment by miquelramirez** [comment]
Hello there,

just to complete @ramonpereira 's report:

 - I have made a PR to ```pyrddl``` with some minor changes I made a while ago on the parser. 
 - There's another PR to ```rddlgym```. This one I just made as I was after replicating this issue on my home machine, where I have a different version of Tensorflow installed than Ramon's.
 - You can find the RDDL generator scripts on the repository https://github.com/miquelramirez/yowie-benchmarks . That's where I am putting the domains that I was looking forward to contribute to the competition (and other stuff, which I am happy to see we're overlapping).

Cheers,

Miquel.

**Comment by thiagopbueno** [comment]
Hi @ramonpereira, @miquelramirez,

I'm glad to know you guys are trying to use tf-plan and the RDDL2Tf suite. Also, thanks for sharing your LQR/LQG RDDL files as I would have to do it myself sooner or later.

Well, the issue is related to some non-trivial interaction between rddl2tf compiler and the tf-rddlsim simulator when there is some mixing of scalar fluents and constants in if-then-else clauses. This is due to the fact that I'm using TensorFlow [tf.where](https://www.tensorflow.org/api_docs/python/tf/where) op to emulate RDDL's if-then-clauses which don't do any kind of shape broadcasting, so I have to do this myself...

Anyway, sorry for the inconvenience. I will fix this issue today and let you know. Also, I will refactor my code this weekend to make it a little bit more robust for handling scalars throughout RDDL.

@miquelramirez: Thank you for the PRs.

Cheers,
Thiago

**Comment by thiagopbueno** [comment]
Hi guys,

Just noticed that you are trying to use **action-preconditions** and **state-invariants** in your RDDL files.

A couple of remarks:
- action-preconditions specifying lower and upper bounds on actions should be written separately (as tf-plan currently uses some very naive static RDDL analysis to extract the bounds)
- state-invariants (and also state-action-constraints) are not currently enforced in tf-plan in anyway.

So, the following 
action-preconditions {
	((u >= -1.0) ^ (u <= 1.0));
    };
should be written as
action-preconditions {
	u >= -1.0;
        u <= 1.0;
    };

and the state-invariants should be 'hard-coded' in the CPFs themselves (possibly using clipping/max/min operators)...

Cheers,
Thiago

**Comment by thiagopbueno** [comment]
Finally fixed the issue with a rather simple solution.

However, in order to optimize stochastic domains tfplan must be used with --mode=online. But, I need to fix a few issues in order to properly handle your domains in the online mode. This weekend I'm gonna work on that and I will let you know when it's fixed...

**Comment by miquelramirez** [comment]
Hi @thiagopbueno, thanks for the comments and looking into this.

Regarding state invariants and action preconditions, we are following here Scott's guidelines (or my reading of his guidelines). I will review the encodings next week - family people like me have busy weekends. 

Cheers, 

Miquel

**Comment by ramonpereira** [comment]
Hi @thiagopbueno, thanks for fixing the issue ;-D
I'm gonna take a look into this tomorrow, and thanks again.

Cheers.

**Comment by thiagopbueno** [comment]
Hi @ramonpereira, I think the issue is solved. Please upgrade to the latest version tf-plan==0.4.7 and make sure the compiler and simulator are also updated to the following versions rddl2tf==0.4.12 and tfrddlsim==0.6.11.

A few important remarks:
1. For stochastic domains you should use tf-plan with the flag --mode=online (it uses a CEC/open-loop-control to handle stochastic transitions)
2. action-preconditions specifying lower and upper bounds on actions should be encoded separately (as tf-plan currently uses some very naive static RDDL analysis to extract the bounds);
3. state-invariants (and also state-action-constraints) are not currently enforced in tf-plan in anyway: (RDDL language allows them, but it is still an open question on how to properly handle them in the general case in a gradient-based planner such as tf-plan);
4. tf-plan maximizes a total reward function, so make sure the reward function is negative in order to encode costs as typically used in LQR and LQG;
5. intermediate-fluents do not get a transition CPF relating their current values with previous values , they are like auxiliary fluents that can depend on the current state, action and previous interm-fluents and basically 'augment' the state representation in order to facilitate the specification of the transition; from what I've seen in your models the fluents "vx(vehicle)", "vy(vehicle)", "v" should not be considered interm-fluents, but just plain old state-fluents.

BTW.. I will work the next weeks on improving the documentation of tf-plan and rddl2tf to make all this assumptions/limitations clearer.

But please let me know if you have further questions. Also, in case you want to discuss research-related topics, I will be glad to have a skype meeting sometime...

Cheers
Thiago
